In [66]:
import numpy as np

In [67]:
# Criando 2 arrays
array1 = np.array([0, 1, 0, 1])
array2 = np.array([0, 0, 1, 1]) 

In [68]:
print ('array1:')
print (array1)
print ('array2:')
print (array2)

array1:
[0 1 0 1]
array2:
[0 0 1 1]


In [69]:
# Imprima a dimensão dessa matriz através do atributo shape
c =  np.c_[array1, array2]
print(c.shape)

(4, 2)


In [70]:
# imprima o conteúdo da matriz resultante da concatenação
np.c_[array1, array2]

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])