# EXERCICIO 10


In [318]:
# Import all necessary libraries.
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np
import cmath
import seaborn as sns
import pandas as pd

In [319]:
# Features to training the classificator
x_train = np.array(['Chinese Beijing Chinese','Chinese Chinese Shanghai','Chinese Macao','Tokyo Japan Chinese'])

# Labels to training the classificator
y_train = np.array(['china','china','china','not china'])

# Test of the classificator
X_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

## Classificador naive Bayes com distribuição de Bernoulli

In [320]:
# Convert a collection of text documents to a matrix of token counts.
vect = CountVectorizer(binary=True)

# Fit and transform X_train into x_train_dtm (document-term matrices - dtm).
X_train_dtm = vect.fit_transform(x_train)

In [321]:
# Counting Matrix
print('Nome dos atributos Bernoulli')
print(vect.get_feature_names())
print('Matriz com a contagem dos atributos')
print(X_train_dtm.toarray())

Nome dos atributos Bernoulli
['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
Matriz com a contagem dos atributos
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [6]:
#Probabilidade 
P_China = 3/4
P_not_China = 1/4

# China
'P(Contagem(Beijing | China) = 1'
'P(Contagem(Chinese | China) = 3'
'P(Contagem(Japan | China) = 0' 
'P(Contagem(Macao | China) = 1'
'P(Contagem(Shanghai | China) = 1'
'P(Contagem(Tokyo | China) = 0'
'sum_(k=1)**(K) contagem(Xk,china) = 6'

#P(Beijing | China)
P_Beijing_china = (1 + 1)/(6+6)
print('Probabilidde Beijing|China', P_Beijing_china)

#P(Chinese | China)
P_Chinese_china = (3 + 1)/(6+6)
print('Probabilidde Chinese|China', P_Chinese_china)

#P(Japan | China)
P_japan_china = (0+1)/(6+6)
print('Probabilidde Japan|China', P_japan_china)

#P(Macao | China)
P_Macao_china = (1 + 1)/(6 + 6)
print('Probabilidde Macao|China', P_Macao_china)

#P(Shanghai | China)
P_Shangai_china = (1 + 1)/(6 + 6)
print('Probabilidde Shanghai|China',P_Shangai_china)

#P(Tokyo | China)
P_Tokyo_china = (0 + 1)/(6+6)
print('Probabilidde Tokyo|China', P_Tokyo_china)

Probabilidde Beijing|China 0.16666666666666666
Probabilidde Chinese|China 0.3333333333333333
Probabilidde Japan|China 0.08333333333333333
Probabilidde Macao|China 0.16666666666666666
Probabilidde Shanghai|China 0.16666666666666666
Probabilidde Tokyo|China 0.08333333333333333


In [2]:
# Not China
'P(Contagem(Beijing | Not China) = 0'
'P(Contagem(Chinese | Not China) = 1'
'P(Contagem(Japan | Not China) = 1'
'P(Contagem(Macao | Not China) = 0'
'P(Contagem(Shanghai | Not China) = 0'
'P(Contagem(Tokyo | Not China) = 1'
'sum_(k=1)**(K) contagem(Xk, Not China) = 3'

#P(Beijing | Not China)
P_Beijing_not_china =(0 + 1)/(3 + 6)
print('Probabilidde Beijing Not China', P_Beijing_not_china)

#P(Chinese | Not China)
P_chinese_not_china = (1 + 1)/(3 + 6)
print('Probabilidde Chinese Not China', P_chinese_not_china)

#P(Japan | Not China)
P_Japan_not_China = (1 + 1)/(3 + 6)
print ('Probabilidde Japan Not China', P_Japan_not_China)

#P(Macao | Not China)
P_Macao_not_China = (0 + 1)/(3 + 6)
print('Probabilidde Macao Not China', P_Macao_not_China)

#P(Shanghai | Not China)
P_Shangai_not_China = (0 + 1)/(3 + 6)
print('Probabilidde Shangai Not China', P_Shangai_not_China)

#P(Tokyo | Not China)
P_Tokyo_not_China = (1 + 1)/(3 + 6)
print('Probabilidde Tokyo Not China', P_Tokyo_not_China)

Probabilidde Beijing Not China 0.1111111111111111
Probabilidde Chinese Not China 0.2222222222222222
Probabilidde Japan Not China 0.2222222222222222
Probabilidde Macao Not China 0.1111111111111111
Probabilidde Shangai Not China 0.1111111111111111
Probabilidde Tokyo Not China 0.2222222222222222


In [3]:
# Prevendo

#P(China |Chinese, Chinese, Chinese, Tokyo, Japan) 

P_Ch_Chi_Chi_Tokyo_Japan = P_China * P_Chinese_china * P_Tokyo_china * P_japan_china
print('Probabilidade', P_Ch_Chi_Chi_Tokyo_Japan)

#P(Not China |Chinese, Chinese, Chinese, Tokyo, Japan)
P_not_Ch_chi_Chi_Tokyo_Japan = P_not_China * P_chinese_not_china * P_Tokyo_not_China * P_Japan_not_China
print('Probabilidade', P_not_Ch_chi_Chi_Tokyo_Japan )


Probabilidade 0.011111111111111112
Probabilidade 0.0027434842249657062



## Existe maior probabilidade de ser Not China

In [325]:
# Instantiate a Bernoulli Naive Bayes model.
nb = BernoulliNB(binarize=None)

In [326]:
# Train the MultinomialNB model.
nb.fit(X_train_dtm, y_train)

BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [327]:
# Transform document into document-term matrix.
X_test_dtm = vect.transform(X_test)

# Perform classification on an array of test vectors X_test_dtm.
y_pred_class = nb.predict(X_test_dtm)
print(vect.get_feature_names())
print(X_test_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[0 1 1 0 0 1]]


In [328]:
# Getting the probabilities for each class.
y_pred_class = nb.predict(X_test_dtm)
print(y_pred_class)
print(nb.predict_proba(X_test_dtm))

['not china']
[[0.19106679 0.80893321]]


## Resposta :

O vetor de teste para indicador positivo para a feature 'chinese' ocorre três vezes, sendo assim o peso é maior do que as ocorrências negativas das features 'japan' e 'to

## Classificação Multinomial

In [345]:
# Features to training the classificator
x_train = np.array(['Chinese Beijing Chinese','Chinese Chinese Shanghai','Chinese Macao','Tokyo Japan Chinese'])

# Labels to training the classificator
y_train = np.array(['china','china','china','not china'])

# Test of the classificator
X_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

In [346]:
# Convert a collection of text documents to a matrix of token counts.
vect_multi = CountVectorizer(binary=False)

# Fit and transform X_train into x_train_dtm (document-term matrices - dtm).
X_train_dtm_multi = vect_multi.fit_transform(x_train)

In [347]:
# Counting Matrix
print('Nome dos atributos Bernoulli')
print(vect.get_feature_names())
print('Matriz com a contagem dos atributos')
print(X_train_dtm_multi.toarray())

Nome dos atributos Bernoulli
['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
Matriz com a contagem dos atributos
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [348]:
#Probabilidade 
P_China = 3/4
P_not_China = 1/4

# China
'P(Contagem(Beijing | China) = 1'
'P(Contagem(Chinese | China) = 5'
'P(Contagem(Japan | China) = 0' 
'P(Contagem(Macao | China) = 1'
'P(Contagem(Shanghai | China) = 1'
'P(Contagem(Tokyo | China) = 0'
'sum_(k=1)**(K) contagem(Xk,china) = 8'

#P(Beijing | China)
P_Beijing_china_ = (1 + 1)/(8+6)
print('Probabilidde Beijing|China', P_Beijing_china_)

#P(Chinese | China)
P_Chinese_china_ = (5 + 1)/(8+6)
print('Probabilidde Chinese|China', P_Chinese_china_)

#P(Japan | China)
P_japan_china_ = (0+1)/(8+6)
print('Probabilidde Japan|China', P_japan_china_)

#P(Macao | China)
P_Macao_china_ = (1 + 1)/(8 + 6)
print('Probabilidde Macao|China', P_Macao_china_)

#P(Shanghai | China)
P_Shangai_china_ = (1 + 1)/(8+6)
print('Probabilidde Shanghai|China',P_Shangai_china_)

#P(Tokyo | China)
P_Tokyo_china_ = (0 + 1)/(8+6)
print('Probabilidde Tokyo|China', P_Tokyo_china_)

Probabilidde Beijing|China 0.14285714285714285
Probabilidde Chinese|China 0.42857142857142855
Probabilidde Japan|China 0.07142857142857142
Probabilidde Macao|China 0.14285714285714285
Probabilidde Shanghai|China 0.14285714285714285
Probabilidde Tokyo|China 0.07142857142857142


In [349]:
# Not China
'P(Contagem(Beijing | Not China) = 0'
'P(Contagem(Chinese | Not China) = 1'
'P(Contagem(Japan | Not China) = 1'
'P(Contagem(Macao | Not China) = 0'
'P(Contagem(Shanghai | Not China) = 0'
'P(Contagem(Tokyo | Not China) = 1'
'sum_(k=1)**(K) contagem(Xk, Not China) = 3'

#P(Beijing | Not China)
P_Beijing_not_china_ =(0 + 1)/(3 + 6)
print('Probabilidde Beijing Not China', P_Beijing_not_china_)

#P(Chinese | Not China)
P_chinese_not_china_ = (1 + 1)/(3 + 6)
print('Probabilidde Chinese Not China', P_chinese_not_china_)

#P(Japan | Not China)
P_Japan_not_China_ = (1 + 1)/(3 + 6)
print ('Probabilidde Japan Not China', P_Japan_not_China_)

#P(Macao | Not China)
P_Macao_not_China_ = (0 + 1)/(3 + 6)
print('Probabilidde Macao Not China', P_Macao_not_China_)

#P(Shanghai | Not China)
P_Shangai_not_China_ = (0 + 1)/(3 + 6)
print('Probabilidde Shangai Not China', P_Shangai_not_China_)

#P(Tokyo | Not China)
P_Tokyo_not_China_ = (1 + 1)/(3 + 6)
print('Probabilidde Tokyo Not China', P_Tokyo_not_China_)

Probabilidde Beijing Not China 0.1111111111111111
Probabilidde Chinese Not China 0.2222222222222222
Probabilidde Japan Not China 0.2222222222222222
Probabilidde Macao Not China 0.1111111111111111
Probabilidde Shangai Not China 0.1111111111111111
Probabilidde Tokyo Not China 0.2222222222222222


In [350]:
# Prevendo

#P(China |Chinese, Chinese, Chinese, Tokyo, Japan) 
P_Ch_Chi_Chi_Tokyo_Japan_ = P_China * ((P_Chinese_china_)**3) * P_Tokyo_china_ * P_japan_china_
print('Probabilidade', P_Ch_Chi_Chi_Tokyo_Japan_)

#P(Not China |Chinese, Chinese, Chinese, Tokyo, Japan)
P_not_Ch_chi_Chi_Tokyo_Japan_ = P_not_China * ((P_chinese_not_china_)*3) * P_Tokyo_not_China_ * P_Japan_not_China_
print('Probabilidade', P_not_Ch_chi_Chi_Tokyo_Japan_ )

Probabilidade 0.00030121377997263036
Probabilidade 0.008230452674897118



## Existe maior probabilidade de ser China

In [351]:
# Instantiate a Bernoulli Naive Bayes model.
nb_multi = MultinomialNB()

In [352]:
# train the model using X_train_dtm
nb_multi.fit(X_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [353]:
# Transform document into document-term matrix.
X_test_dtm_multi = vect_multi.transform(X_test)

# Perform classification on an array of test vectors X_test_dtm.
y_pred_class_multi = nb_multi.predict(X_test_dtm_multi)
print(vect.get_feature_names())
print(X_test_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[0 1 1 0 0 1]]


In [355]:
# Getting the probabilities for each class.
y_pred_class_multi = nb_multi.predict(X_test_dtm_multi)
print('Probabilidade Multinomial')
print(y_pred_class_multi)
print(nb_multi.predict_proba(X_test_dtm_multi))

Probabilidade Multinomial
['china']
[[0.58742949 0.41257051]]


## Resposta:

O motivo dessa classificação é que as três ocorrências do indicador positivo 'chinese' no vetor de test superam (tem maior peso) do que as ocorrências dos dois indicadores negativos 'japan' e 'tokyo'. No Classificador Bernoulli os atributos são Booleanos independentes,  e ele não conta os elementos repetidos
diferente do Multinomial os atributos são discretos.